docsifyjs/docsify

README.md

add showcase at README.md

---

README.md

add showcase of Mybatis-Plus

---

docs/configuration.md

Fix a typo

---

docs/more-pages.md

Update dictory structure in more-pages.md

---

README.md
dev.html
package.json
src/themes/basic/_coverpage.css
src/themes/basic/_layout.css
src/themes/buble.css
src/themes/dark.css
src/themes/vue.css

See commits for details.
> I did **not**:
> * rebuild
> * bump the version
> * update the `yarn.lock` file as I'm not using yarn

fix some minor issues

---

src/plugins/search/search.js

fix search plugin match bug

---

src/core/render/compiler.js
src/core/route/hash.js

in toURL test for anchor links and if so prepend the currentPath to t…he generated path. fixes #142.

Properly handle anchor links local within a file. Fix #142

---

dev.html
docs/_navbar.md
docs/configuration.md
docs/de-de/_navbar.md
docs/de-de/configuration.md
docs/index.html
docs/zh-cn/_navbar.md
docs/zh-cn/configuration.md
src/core/config.js
src/core/render/index.js
src/themes/basic/_layout.css

feat(render): add mergeNavbar option, close #125, #124

---

README.md

I started the job search this year as a new MS in CS grad and as I continued to build up my resources for the job interview process, it became hard to keep track of everything.
So I ended up using `docsify` to create [this website](http://fvcproductions.github.io/hire-me) called **hire-me** of all the relevant resources I used when going through the job interview process in the tech industry. 
I found `docsify` so much easier to use than other options out there and was hoping to get my site shown in the showcase section so that other developers recognize that it can be used in a multitude of different ways.
Thanks again for creating such a great static site generator!
---

Add hire-me to showcase section 💼

---

docs/more-pages.md

Pretty dir tree

---

README.md

Add vue-amap into README.md

---

README.md

And here's an additional report if you're interested!

Add license report

---

README.md

Add samlify in README.md

---

docs/configuration.md

Update doc for external link target

---

lib/plugins/search.js

use regular filter picturn in search

Filter picture

---

README.md

Added palettify - a small project that eases adding dynamic styles using Color palettes.

docs: Add palettify in Showcase

---

build/build.js

Remove unnecessary moduleName option from rollup config for plugins

---

src/themes/basic/_layout.css

give the navbar some line-height

---

README.md

add vue-data-tables to the showcase

---

docs/plugins.md

add doc for Edit on github plugin

---

src/core/config.js

bugfix: config.js里面应为routerMode属性而非routerModel

---

docs/vue.md

fix: missed symbol

---

README.md

In my humble opinion, the doc of this project might have a better file structure for multiple languages

Add vue2-datatable-component in Showcase

---

docs/deploy.md

docs: Deployment guide for GitLab Pages

---

README.md

Thanks for such a great documentation tool!

Add another fan of docsify!

---

.gitignore
build/release.sh

By this PR I hope that the last checkbox in this PR-template no more needed.
And other problems described in #282 (item 1) will be avoided.

improve dev: ignore ./lib , force add ./lib on release

---

src/plugins/search/search.js

#257 fix duplicate results in search

---

README.md

Add rnback website to showcase

---

docs/vue.md

A nested code block in docs/vue.md is not rendered correctly.
This patch adds backticks to fix this issue.

fix a broken code block

---

dev.html
docs/index.html

Move the `<script>` tags to above the `</body>` tag in order to make these files count as valid HTML.

Move script tags above closing body tag

---

docs/helpers.md
src/core/render/compiler.js
src/themes/basic/_layout.css

feat: add helper for disabled link, fixed #295

---

src/themes/basic/_layout.css
src/themes/vue.css

fix: sidebar style issue on firefox, fixed #184

---

docs/more-pages.md
src/core/render/compiler.js

**Should I include the file in themes/ folder ?**
Sorry for the previous PR https://github.com/QingWei-Li/docsify/pull/298, I seems the doc is correct, but there is a bug in code.
Also, find any problem in {docsify-ignore}, second contiunous {docsify-ignore} still show in sidebar

fix {docsify-ignore-all} and {docsify-ignore} bug

---

docs/plugins.md
package-lock.json
package.json
src/core/render/compiler.js
src/plugins/zoom-image.js
src/themes/basic/_layout.css

fix: zoom image plugin issue, fixed #187

---

README.md

Add zooming to showcase

---

docs/de-de/helpers.md
docs/helpers.md
docs/zh-cn/helpers.md
src/core/render/compiler.js
src/themes/basic/_layout.css
src/themes/vue.css

feat: github task lists, close #215

---

docs/zh-cn/more-pages.md

translate zh-cn doc for more-pages.md

translate zh-cn doc for more-pages.md

---

docs/deploy.md

Just clarifying the need for a `.nojekyll` in the deployment location

Update deploy.md to specify .nojekyll use

---

docs/zh-cn/configuration.md
docs/zh-cn/deploy.md
docs/zh-cn/helpers.md
docs/zh-cn/markdown.md
docs/zh-cn/plugins.md

docs:Improve the translation

---

README.md

Add one more component, that use docsify

Add vue-sticker in Showcase section

---

README.md

Hello guys,
Thanks you for your great work :). Your tool help me lot to develop a website documentation and API references (if you are interested see https://romakita.github.io/ts-express-decorators/#/api/index).
See you and great work again !
Romain

chore: Add website example based on docsify

---

README.md

Add a  vue-orgchart showcase whose doc based on docsify.

chore: add vue-orgchart in showcase section

---

README.md

Add Vue Content Loading to showcase

---

docs/ssr.md

---
A JSON file can't use single quotes for string values, and `<script>` tags should be inside/at the bottom of the `<body>` tag. This PR fixes that.

Fix invalid package.json/HTML references

---

README.md

Add preact-analysis to showcase

---

README.md

Add CBoard doc example created by docsify. 
Thanks for your work

CBoard Usercase

---

src/core/event/sidebar.js

fix:修复中文文件名导致侧边栏不正确问题 (#353)

---

docs/deploy.md

Adding double-space so the !> is formatted correctly

---

docs/deploy.md

Just following up on #377; here's a first crack at this. It might need some changing depending on the ideal Tone of Voice, so suggestions are welcome.
Closes #377

Adding Firebase Hosting deployment documentation

---

docs/helpers.md

There's nothing fancy on this commit

Fixed a little error

---

docs/configuration.md

> Only coverpage is loaded when ~~When~~ visiting the home page.

chore: typo

---

.gitignore
package-lock.json
package.json

- Add rimraf to remove file (Windows/Unix/Mac compliant)
- Add concurrently module to run node app and nodemon concurrently

chore: Update dev task in package.json

---

docs/de-de/markdown.md
docs/zh-cn/markdown.md

The `marked` project has moved to a GitHub org and the url has changed.

Update url to markedjs

---

docs/zh-cn/configuration.md

zh-cn configuration part has duplicate maxLevel description.

fix duplicate maxLevel

---

docs/index.html

make the ad show more beautiful

upgrade docsify-plugin-codefund

---

docs/cover.md

A very simple typo on the `cover.md` page.

Fixed a typo in cover.md

---

docs/de-de/deploy.md
docs/deploy.md
docs/zh-cn/deploy.md

docs: add netlify

---

docs/configuration.md

This was `history` when it should have been set to `hash`. It also described the correct value in the example, which was misleading.

docs: Correct default value for routerMode

---

src/core/event/scroll.js

fix path include chinese character cause hilight bug

---

package.json

feat: add unpkg field, close #531

---

docs/index.html

official domain name is changed, which cause the issue. change to use the newest plugin.

fix the codefund load error

---

docs/more-pages.md

The documentation for how to create nested sidebars was unclear, and I could not find it anywhere else. After experimenting, I discovered the tactic and felt it should be in the docs.
* [x ] Make sure you are merging your commits to `master` branch.
* [x ] Add some descriptions and refer relative issues for you PR.
* [x ] DO NOT include files inside `lib` directory.

Updated sidebar documentation to clarify nesting

---

README.md

Fix typo and update open collective gold sponsor URL

---

src/plugins/zoom-image.js

- Ignore images outside of main content area (e.g. logo, sidenav icons, etc.)
- Ignore linked images (previous behavior broke linked images)
Fixes #520
* [ x ] Make sure you are merging your commits to `master` branch.
* [ x ] Add some descriptions and refer relative issues for you PR.
* [ x ] DO NOT include files inside `lib` directory.

Fix zoom-image target elements

---

docs/plugins.md

Add docsify-tabs to list of plugins

---

docs/vue.md

This PR corrects the Vue demo example in the docs, for newbies like me that simply copy-paste the example, and wonder why it doesn't work.

[docs][vue-demo][minor] add ID attribute in div element

---

docs/helpers.md
src/core/render/compiler.js

Closes https://github.com/docsifyjs/docsify/issues/659
-----

feat: custom heading ID

---

src/core/render/index.js
src/themes/basic/_coverpage.styl

A temporary solution, I will refactor this part of the code in the next major version.

fix: cover button style, fixed #670, fixed #665

---

src/core/render/compiler.js

fix(compiler): import prism-markup-templating, fixed #672

---

docs/_media/example.js
docs/embed-files.md
src/core/render/compiler.js
src/core/render/embed.js

See `docs/embed-files.md` how to use the feature

Provide code fragments feature

---

src/themes/dolphin.styl

Dolphin is a blue theme based on the theme vue, using the font [Thasadith](https://fonts.google.com/specimen/Thasadith) as default.

Add new theme "dolphin"

---

docs/ssr.md

Fix typo in Now SSR example code snippet

Fix typo in Now SSR example code snippet

---

src/core/render/emojify.js
src/plugins/emoji.js

Fix github assets url

---

index.html

align production html to dev index.html 

---

src/plugins/search/search.js

Updates the search plugin and adds scoring to search results. Search results that contain multiple keywords are scored higher than those that contain only one and appear first on the result list.
Headings add score +3, content matches +2. How will that work?
* For two keywords, a heading containing only one will be scored lower than body text containing both. But if a heading contains both, it will score higher than body text containing both.
* For 3 keywords, a heading containing 2 of the 3 will score the same as body text containing all 3
* For 4 keywords, a heading containing 3 of the 4 will score higher than body text containing all 4
------
Before:
------
After:

add scoring and sort to search plugin

---

README.md
docs/README.md

**Summary**
Fixes https://github.com/docsifyjs/docsify/issues/826. Link to showcase section in readme in [awesome-docsify](https://github.com/docsifyjs/awesome-docsify) from [docsify](https://github.com/docsifyjs/docsify)'s readme and [website](https://docsify.js.org/#/?id=examples).
To avoid wasting your time, …

Fix #826: Link directly to showcase in readme and website

---

docs/deploy.md

[Develop] : Add deployment instructions for ZEIT Now

---

package-lock.json
package.json

**Summary**
There where approx of 90 high-security alerts and the npm audit fix PR merge recently was for the `develop` branch which I think is not currently published. Made one to fix them
_Will merge this soon if not getting a review as this is quite an urgent step_
NA
NA
Closes few of the audit issues
To avoid …

[master branch ] fix: package security alerts

---

package-lock.json
package.json

Reverts docsifyjs/docsify#950
As `develop` -> `master` is used for releasing so this is already fixed for `develop`

Revert "[master branch ] fix: package security alerts"

---

.github/FUNDING.yml

**Summary**
Added sponsor button
NA
---

chore: added sponsor button

---

.github/FUNDING.yml

Fixed FUNDING.yml 

---

src/core/render/tpl.js
src/plugins/search/component.js

**Summary**
Changes related to issue #945 (about accessibility)
Before |  After
:-:|:-:
Please leave a comment here or in the issue #945 if you have any suggestions to …

fix #945 - Improve accessibility

---

src/core/render/tpl.js
src/core/util/core.js

**Summary**
fixes #972
when 'logo' is set, 'name' is not set correctly inside the 'alt.
fix, make the 'name' parsed the same as without 'logo' set.
when  `logo` is set, …

[fix]#972 when 'logo' is set, 'name' is not set correctly inside the 'alt' as same as without 'logo' set.

---

docs/deploy.md

**Summary**
Without the redirect images are not displaying in Amplify after deploying. Once added the redirect all PNGs showed up.
---

Added a redirect for images to show up in Amplify

---

docs/configuration.md

docs: about cache

---

package.json

**Summary**
Add modified files to the staging area while executing lint script as part of `pre-commit hook`.

fix(chore): stage modified files while executing lint script as part of pre-commit hook

---

src/core/render/tpl.js
src/core/util/core.js

fix https://github.com/docsifyjs/docsify/issues/990

chore: removed the escaping of the name of sidebar

---

.github/stale.yml

chore: add config

---

.gitpod.yml
README.md

**Summary**
Hi! :slightly_smiling_face: 
This Pr contains updates to improve the Gitpod setup. Here is a list of them:
- exposes port: 3000 and opens the preview automatically.
- add VS Code extension for stylus support. 
- remove the `build` script from the Gitpod setup to make the server startup fast.
- update Gitpod description in the README.
-  add VS Code extension for stylus support.
You have tested in the following browsers: (Providing a detailed version …

Gitpod setup enhancements.

---

src/core/render/utils.js

fix #1115 , Image resize in % doesn't work.
checked all use cases in documentation , it is fine.
**Summary**
Fix  Image resize in % doesn't work about the `regex`, details in this issue #1115. …

[fix #1115] Image resize in % doesn't work.

---

docs/cover.md

**Summary**
for #1132
Support multiple covers, more than one, right?
If yes, you can also merge docsifyjs/docs-zh#18、docsifyjs/docs-es#2、docsifyjs/docs-ru#6、docsifyjs/docs-de#1
**Other …

[Docs] Update cover.md

---

docs/configuration.md

Fix typo on `externalLinkRel`

---

docs/index.html
index.html

**Summary**
Fix Chinese document edit button error.
---

fix Edit Document

---

docs/configuration.md

**Summary**
The first place I went to when noticing this issue was the documentation for the homepage. So that's where I thought it was best to document it.
I'm not a …

Fix #1131: Document homepage active link pitfall

---

src/core/render/emojify.js

Fix: emoji +1 and -1 not rendering

---

docs/index.html

Reverts docsifyjs/docsify#1182

Revert "Updated docs site dark and light mode with switch and redesigned search bar using docsify-darklight-theme"

---

src/plugins/search/search.js

**Summary**
fix search can not search the table header.
Close #1255 
---

fix: search can not search the table header

---

cypress/fixtures/tpl/docs.index.html
cypress/integration/sidebar/config.spec.js
docs/index.html
docs/plugins.md

**Summary**
Fixes #1258 
Removed the existence of codefund in docsify, (i.e. codefund documentation and the plugin used by docsify)
---

Removed codefund docs and plugin [Fix#1258]

---

docs/_navbar.md
docs/index.html
index.html

**Summary**
close #1269 
Russian's using this domain: https://docsify-ru.js.org/, So change the `ru` of the main repository to `ru-ru`
---

fix:  Russian language link error

---

docs/helpers.md

**Summary**
Modify Chinese in English docs.

docs: Update helpers.md

---

docs/cdn.md

**Summary**
docs: update other cdn. 
add `unpkg.com`.

docs: update other cdn

---

docs/index.html
index.html

fix: sidebar horizontal scroll bar

---

src/core/render/compiler.js

fix: Cannot read property level of undefined

---

src/plugins/search/search.js

**Summary**
fix: search cannot search list content
```
balabala...
* this is content
* this is content
```

fix: search cannot search list content

---

.github/ISSUE_TEMPLATE/config.yml

chore: Create issues config.yml

---

docs/quickstart.md

**Summary**
When I used the `cd docs && python -m SimpleHTTPServer 3000` in py3,  it cant find the module.
According to the [docs](https://docs.python.org/2/library/simplehttpserver.html) and [reference](https://stackoverflow.com/questions/7943751/what-is-the-python-3-equivalent-of-python-m-simplehttpserver), 
> The SimpleHTTPServer module has been merged into http.server in Python 3.0.
Add cmd for py3.
You have tested in the following browsers: (Providing a …

docs: update the cmd of python setup serve in py3.

---

package-lock.json
package.json

fix: upgrade dompurify from 2.2.2 to 2.2.6

---

package-lock.json
package.json

**Summary**
Required for testing on ARM-based Macs.

chore: update playwright to 1.8.0

---

docs/README.md
docs/index.html

docs: Update Vercel logo link

---

src/core/fetch/index.js
src/core/util/core.js
test/unit/core-util.test.js

Based on #1510 .
Add tests for `isExternal()` for currently known security vulnerability issues.
**Summary**
tests.

test(unit): add test cases on isExternal.

---

src/plugins/search/search.js
test/e2e/search.test.js

feat: Support search when there is no title

---

.github/workflows/test.yml

see https://github.com/docsifyjs/docsify/runs/2064836724?check_suite_focus=true
```
E: Unable to locate package libevent-2.1-6
E: Couldn't find any package by glob 'libevent-2.1-6'
E: Couldn't find any package by regex 'libevent-2.1-6'
```

chore: fix microsoft/playwright-github-action error

---

docs/deploy.md

Updates the deploy section of the docs, replacing Zeit with Vercel.
Docs

docs: Update deploy to change Zeit to Vercel

---

docs/index.html

Fix search for missing pathNamespaces
docs, Fix the problem that the search in English documents may search other languages

chore: Fix search for missing pathNamespaces

---

docs/plugins.md

Add a link about Pagination plugin to document.
Docs
None.

docs: add a link about plugin Pagination

---

docs/index.html
index.html

Update Edit Document using develop branch
Docs, Prevent editing documents from being committed to the wrong branch

chore: Update Edit Document using develop branch

---

package-lock.json
package.json

fix: upgrade dompurify from 2.2.7 to 2.2.8

---

package-lock.json
package.json

close #1599 
fix missing dependencies.

fix: upgrade dompurify from 2.2.8 to 2.2.9

---

src/core/render/emojify.js

Fixed regex. A word (\w) is only [a-z0-9_].
Bugfix

emojify: correctly fix missing +1, -1 from #1162, 1a09ce3a

---

README.md

Improves sentence flow in the repository readme. Might not be necessary, but I think it does make the README better.
Docs

Improve README.md sentence

---

src/core/util/str.js
src/plugins/search/search.js

fix #1867 
Remove `docsify-ignore` tag in slug before generate local storage index.
Bugfix

fix: fix docsify-ignore in seach title.

---

docs/deploy.md

Uses the updated the name of the default GitHub branch 
- Docs
- Closes #1884 

docs: Update GitHub default branch from to 'main'

---

package-lock.json

Dependency upgrade about the annoying warning.
Other

chore: upgrade caniuse-lit.

---

packages/docsify-server-renderer/package-lock.json
packages/docsify-server-renderer/package.json

As @sy-records  is aware of that the latest released not update the related `docsify-render` in #1914. and it will make the build crush.
Fix dependencies in this package.

fix: fix docisify-render denpendency.

---

.github/workflows/test.yml

Add build action for `server-render` in case of building failed.
Repo settings

ci: add server-render build.

---

src/themes/dark.styl

style: change table tr style for dark theme

---

docs/language-highlight.md

I couldn't get a prism typescript language grammar to work until I realised that script order mattered.   
This might not be the best language or format for this, but I think it probably belongs in the documentation in some manner.

Describe ordering requirement for prism script tag

---

docs/index.html
docs/themes.md
index.html

docs: Fix missing dolphin theme

---

.github/workflows/test.yml

Remove the duplicated ci config.
Bugfix

chore: remove ci duplicated config

---

docs/more-pages.md

Update the option 2 to use `docsify-ignore`.
Docs

chore: docsify-ignore config polish.

---

.github/FUNDING.yml

Use base config: [.github](https://github.com/docsifyjs/.github/blob/main/FUNDING.yml)
Repo settings

chore: remove funding

---

src/core/render/compiler.js
src/core/render/compiler/headline.js
src/core/render/utils.js
test/unit/render-util.test.js

Refine docsify-ignore and add test cases.
Refactor

update: refine docisfy-ignore.

---

README.md

Fix the broken sponsors list and polish the text.
Other 
Yes
No
No

chore: sponsors list fix.

---

build/build.js
build/cover.js
build/emoji.js
build/mincss.js

chore: optimize compressed css script

---

docs/index.html

Causes Carbon ad to fail to load, Fixed it now.
Bugfix
No

fix: carbon broken

---

docs/quickstart.md

docs: Fix spelling mistake

---

build/release.sh

Add test run to release script per [`TODO`](https://github.com/docsifyjs/docsify/blob/8ef9a3cd036bc86278709199e1da19da36f04ed1/build/release.sh#L18) in [`/build/release.sh`](https://github.com/docsifyjs/docsify/blob/develop/build/release.sh).
N/A
No
N/A

build: Add test run to release script

---

docs/emoji.md
src/core/render/emoji-data.js

Found updated github emojis need to sync.

chore: Sync emoji data with GitHub emoji API

---

docs/themes.md

Include list of CSS vars in docs. NOTE: Chinese language docs should also be updated to include these.

docs: Included relevant CSS vars to theme docs.

---

src/core/render/compiler.js

fix(sidebar): remove ignored headings and children
