docsifyjs/docsify

src/util.js

在做emoji替换的时候，会把`::`替换成`<img class="emoji" src="https://assets-cdn.github.com/images/icons/emoji/.png" alt="" />`，导致图片显示问题。

fix emoji replacing error

---

docs/_coverpage.md

As `## docsify` is the new title of the `README.md`, *Get Started* should link to that.

Correctly link Get Started

---

src/themes/basic/_coverpage.css

This changes the look of links in the blockquote of the coverpage (as referenced in #82). It now looks like this:

fixed look of links in blockquote

---

README.md
docs/README.md
docs/_coverpage.md
docs/_sidebar.md
docs/cover.md
docs/custom-navbar.md
docs/more-pages.md
docs/quickstart.md
src/themes/basic/_coverpage.css

This fixes some syntactical and semantical errors in the "Getting started"-part of the documentation.
Also, the browser support noted in the main README was updated from IE9+ to IE10+ as in docs/README.

Update docs: Getting started

---

src/themes/basic/_layout.css

Currently when you open a docsify page, the top nav immediately comes up while the page is still loading. Clearly this is not desired, and this PR fixes it.

Fix nav showing while loading

---

CHANGELOG.md
HISTORY.md
README.md
docs/README.md
docs/_sidebar.md
docs/cdn.md
docs/configuration.md
docs/cover.md
docs/custom-navbar.md
docs/deploy.md
docs/helpers.md
docs/language-highlight.md
docs/markdown.md
docs/more-pages.md
docs/plugins.md
docs/pwa.md
docs/quickstart.md
docs/sw.js
docs/themes.md
docs/vue.md
docs/write-a-plugin.md
docs/zh-cn/_sidebar.md
src/themes/basic/_coverpage.css
src/themes/basic/_layout.css
src/themes/buble.css
src/themes/dark.css
src/themes/vue.css

* updated English docs
* sorted css src files
* fixed main md files
---
FYI: Building fails on Windows due to `fsevents` being OSX only.

Update English docs and sort css

---

lib/plugins/ga.js

On https://docsify.js.org/#/quickstart
send "#/quickstart" instead of "https://docsify.js.org/#/quickstart"

GA: Send hash instead of complete href

---

README.md

I migrated from docpress, very happy!
Not related question, but I don't know why search is not enabled:
https://github.com/Kikobeats/js-mythbusters/blob/master/docs/index.html#L27

Add JS MythBusters to showcase

---

docs/README.md
docs/configuration.md
docs/de-de/configuration.md
docs/de-de/helpers.md
docs/helpers.md
docs/zh-cn/configuration.md
docs/zh-cn/helpers.md
src/core/config.js
src/core/render/compiler.js
src/core/router/util.js

feat: ignore to compiled link, fixed #203

---

package.json
src/core/index.js

如果在 document ready 前初始化 Docsify，后续引入的插件里 hook 不会被触发（如 afterEach）。

ensure document ready before init Docsify

---

packages/docsify-server-renderer/README.md

The docsify server renderer package is published at `docsify-server-renderer` but README.md refers to `docsify-server-render`

fix yarn add command

---

package.json
src/core/event/scroll.js
src/core/fetch/index.js

花了大半天做了几个修改，还有几个问题找不到在哪改，感觉好多细节问题啊……
已修正问题：
<details> 
<summary>1. 加载谜之路径侧边栏</summary>
<br>
这项修改我是存疑的，不知道作者初始意图是什么，但在这里我个人认为 basePath 与文档文件路径再叠加一次有点奇怪吧？应该是bug
</details>
<details> 
<summary>2. 侧边栏不能点亮问题</summary>
<br>
在看代码之前，我一直以为这个是feature，翻了一下发现不对劲啊？明明有实现的，然后打印信息看了一下。
结果是这样的：
然后我看了一下定位的那个元素
。。。
</details>
<details> 
<summary>3. 平滑滚动以及点击反馈修正</summary>
<br>
问题2的衍生问题。
这里的问题是，如果右侧足以容纳若干项定位点，那么左侧导航将被永远锁在右侧最顶上的那一个。下面的你点了也不会有反馈，尽管url会变化。
这里我为了在点击后进行 scrollIntoView 滚动时不让 scroll 事件起效引入了 tweezer.js
弃用 scrollIntoView 的原因是我发现 scrollIntoView 是异步的，给出的选项太少了，滚动不能调速度也没有 callback，这就导致我根本不可能在滚动时关掉事件完成后弄回来。
平滑滚动就是一个副产品了。
</details>
<br>
其他已知问题：
<details> 
<summary>1. 某情况下点击反馈无效</summary>
<br>
跟问题3类似的场景，也就是右边容纳了不止一个定位点。
当你点击了最底下的那个边栏导航，然后刷新。
点亮的项就会锁在更上面一个，与当前url中id相同的一项无法点击。
</details>
<details> …

fixed sidebar item inactive issue & fixed _sidebar.md 404 issue & smooth scroll

---

docs/plugins.md

add doc for `react` and `vue` demo box plugin
[Vue](https://njleonzhang.github.io/docsify-demo-box-vue/) and [React](https://njleonzhang.github.io/docsify-demo-box-react/) are both supported.
sorry for poor english, you may need help to revise the description

add doc for react and vue demo box plugin

---

docs/plugins.md

Adds a new section to the `plugins` page for a plugin that adds a "Click to copy" button to all preformatted code blocks.

docs: Add new copy-to-clipboard plugin

---

dev.html
docs/index.html
src/core/event/scroll.js

Docify is not able to scroll to anchor in IE. This issue can be reproduced by using IE (for example IE 11) to visit docsify website and clicking link on sidebar.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY), property `scrollY` is not available in IE. Meanwhile, `pageYOffset` property is an alias for the `scrollY` property and is available in IE 9+ and all other browsers (details [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset)).
The other commit will add extra meta tag in html files, to force IE browsers to render page using latest version of IE available. Otherwise, it might use IE 7 to render, which will cause issues. 

fix scroll issue in IE

---

src/plugins/search/component.js
src/themes/basic/_layout.css

Hi, I would like to propose a change to search plugin. Currently, only the title of search result is clickable. It might sound a bit weird for users as the search content is plain text and cannot redirect them.
This PR will make the complete area clickable by wrapping the whole area with a tag.
One thing to notice is that the search keyword will be rendered using theme color, the same color when mouse hovered. To distinguish them, I made the keyword also bold.
How it looks when displaying search result:
How it looks when mouse hovered:
Should work fine with all default themes. But perhaps not a very well-designed. Let me know if you have any feedback.

Feature propose: Make whole search result area clickable

---

docs/more-pages.md

{docsify-ignore-all} not work properly when adding after H1, but it work when adding after H2

{docsify-ignore-all} not work properly

---

build/build.js
docs/plugins.md
src/plugins/gitalk.js

Inspired by disqus plugin
thanks to the author

feat: add gitalk plugin

---

src/plugins/disqus.js

fix #317, disqus plugin make page refresh continuously.
```
location.href = location.href.replace('/-/', '/#/')
```
如果打开的是根目录，就会出现`/` 会被route改成`/#/`，然后这句话由把href改回`/`无限循环了。
我简单做了个保护。。。单由于不太理解这句话的含义，所以也不知道这样改有没有副作用。我在我的环境里没测试出问题。

fix issue disqus plugin issue

---

package-lock.json
package.json

Upgrade `marked` for security reasons:
https://nvd.nist.gov/vuln/detail/CVE-2017-17461
https://nvd.nist.gov/vuln/detail/CVE-2017-1000427

updated deps to fix security (marked upgraded)

---

docs/configuration.md

Based on my interactions with Docsify and the context to that line, it seems as though that may have been a quick typo! I'm just fixing it, as it said the default is `_self` not `_blank` :)

Fixing default option for externalLinkTarget

---

src/core/fetch/index.js
src/core/render/index.js

When a file is a HTML, the markdown parse the file. This behavior isn't not expected. This PR fix that.

fix(render): Disable markdown parsing when the file is an HTML

---

docs/configuration.md
src/core/fetch/index.js

fallbackLanguages give the possibility to configure a list of languages which must used the default language when a page is missing in the requested language.
* type: `Array<string>`
List of languages that will fallback to the default language when a page is request and didn't exists for the given local.
Example: 
- try to fetch the page of `/de/overview`. If this page exists, it'll be displayed
- then try to fetch the default page `/overview` (depending on the default language). If this page exists, it'll be displayed
- then display 404 page.
```js
window.$docsify = {
fallbackLanguages: [
"fr",
"de"
]
};
```
***

feat(fetch): Add fallback languages configuration.

---

src/core/event/index.js
src/core/render/index.js

Navbar is added to the DOM. It's not necessary when loadNavbar is falsy :)

fix(navbar): Now Navbar isn't append to DOM when loadNavbar is falsy

---

docs/configuration.md
docs/de-de/configuration.md
docs/zh-cn/configuration.md
src/core/fetch/index.js
src/core/render/index.js

This feature add the notFoundPage options to customize the default 404 page
with a markdown file. It also support the localisation.

feat(config): Add 404 page options.

---

src/themes/buble.styl

Set `.markdown-section pre`'s `position` to `relative` to fix _Copy code_ button not displaying correctly.
From issue #447

Fix 'copy code' button displaying incorrectly

---

docs/plugins.md
docs/zh-cn/plugins.md

add plugin for codefund

---

docs/_navbar.md

Adding Spanish

---

docs/configuration.md
docs/de-de/configuration.md
docs/zh-cn/configuration.md
src/core/render/compiler.js
src/core/render/index.js
src/core/render/tpl.js

feat: add logo option, #264

---

src/plugins/front-matter/index.js

--- 
Switching frontmatter config from `vm.config` to separate `vm.frontmatter` solves cross-polluting when going from page with frontmatter to page without it.
Also switching from `attributes.config` to plain `attributes` as the first one requires every page to have frontmatter in format below, which is unnecessary and counterintuitive (beacuse of missing documentation ofc).
```
---
config:
- author: @petr
---
```
Closes #548

frontmatter: Move frontmatter content into vm.frontmatter

---

src/core/render/compiler.js
src/core/render/tpl.js
src/themes/basic/_layout.styl
src/themes/buble.styl
src/themes/dark.styl
src/themes/vue.styl

This PR is trying to fix nested toc style issue below.
**Before**
**After**
Here is my solution.
1. Remove recursive toc outer tag `li`
2. remove `.sidebar li` marginLeft
3. add `.sidebar ul` marginLeft
Related issue:
https://github.com/docsifyjs/docsify/issues/421
https://github.com/docsifyjs/docsify/issues/519

Fix nested toc style issue on sidebar

---

src/plugins/search/search.js

Closes https://github.com/docsifyjs/docsify/issues/614
- Currently, if configured in `auto` mode, search plugin gets all relative links in `document` and trying to index them. 
- This PR changes the query selector from **all relative links** to **all top level sidebar nav links**.
> Reason is that only these links (and only them should) link to the markdown files of a project. If there is any file link in main content not listed in `_sidebar.md`, it should be listed there.
> Also removed unnecessary `helper` object.

[search plugin] fix fetching unnecessary links issue

---

src/core/render/compiler.js

Closes https://github.com/docsifyjs/docsify/issues/625
Note: Not covering https://github.com/docsifyjs/docsify/blob/master/src/core/render/compiler.js#L219-L221 because there shouldn't be a case where you would attach`target` config to a `mailto` link.

Remove target for mailto links

---

docs/README.md

- Change "What is it" heading to "What it is", as it's not a question
- Expand SSR acronym
- Slightly reword some passages for clarity

README: various small tweaks

---

src/themes/vue.styl

CSS style for functions is specified in buble.styl only. Thus, for example, bash commands from prism-bash.js (function section) are not highlighted. You can add a new CSS style with the right color you think fits better  :).

Update vue.styl (issue #635)

---

src/core/render/compiler.js
src/core/render/embed.js

Adds support for embedding `.mmd` mermaid files.

Support embed mermaid files .mmd

---

package-lock.json
package.json
src/core/render/compiler.js
src/core/render/embed.js
src/themes/basic/_layout.styl

feat: upgrade marked to 0.5.x, fixed #645, close #644

---

docs/plugins.md
src/core/render/tpl.js
src/plugins/search/component.js
src/plugins/search/index.js

Allow user to configure whether or not to hide other sidebar content while showing searching results.
Related issue: https://github.com/docsifyjs/docsify/issues/535
-----

feat: add hideOtherSidebarContent option

---

src/core/render/index.js

Closes https://github.com/docsifyjs/docsify/issues/666
`marked@0.5.1` renders image without `<p>` wrapper, which is different from `marked@0.3.12`.
Updating match regex in `_renderCover` solves the problem.
-----

fix: customising cover page background colour not working

---

src/core/render/embed.js

Closes https://github.com/docsifyjs/docsify/issues/664
`prerenderEmbed` is using the actual cached value when there is a hit. The value (an array) gets cleared somehow during processing https://github.com/docsifyjs/docsify/blob/master/src/core/render/index.js#L159. By the time the cached value is hit again, though the value is not `undefined`, the content is empty. Hence 404 shows up.
Using a copy of cached value solves the problem.
-----

fix: unexpected 404

---

src/core/render/compiler.js
src/core/render/embed.js
src/core/render/index.js
src/themes/basic/_coverpage.styl

fix(cover): Compatible with legacy styles, fixed #677

---

docs/plugins.md
src/plugins/search/index.js
src/plugins/search/search.js

Local storage stores data per domain. [[1]](https://stackoverflow.com/a/4201249)
> It's unique per `protocol://host:port` combination.
Take the example in https://github.com/docsifyjs/docsify/issues/697:
- https://ramblerw.github.io/blog-money
- https://ramblerw.github.io/python3
They are under the same domain `https://ramblerw.github.io`. Thus, they share the same search index data.
Introduces a new option: `namespace`, to avoid local storage collision.
If `namespace` is set, search index data will be saved under a namespaced key, e.g. `docsify.search.index/docsify-test-namespace`.
Fixes https://github.com/docsifyjs/docsify/issues/697
-----

feat(search-plugin): add namespace option

---

src/core/render/compiler.js

Update getAndRemoveConfig regular expression for prevent cases, when header has name like `# foo::bar::baz`. 
We use docsify for perl, our regular case: `### Some::Module`, and without fixed regex we have header like `### Some:`.
Compatible with FireFox.

Fix getAndRemoveConfig regex

---

src/themes/basic/_layout.styl

On mobile Safari, 100% width iframes can have horizontal overflow from their parent container. This modification to the base theme fixes it.
Fixes #781

Fixed iframe overflow bug for mobile Safari

---

package-lock.json
package.json
test/_helper.js
test/fixtures/default/README.md
test/fixtures/simple/README.md
test/fixtures/simple/other-page.md
test/integration/render.js
test/integration/router.js
test/render.js
test/unit/render.js

Improving test setup which allows now to init and run docsify against fixture directories which include README.md and any other files. By default an empty README.md is used (for unit tests).
@docsifyjs/core feedback welcome

Improve test setup

---

docs/deploy.md

This is to help users to be able to publish Docsify with AWS Amplify, so they don't get stuck on redirect rules and hash state issues.
* [Y] Make sure you are merging your commits to `master` branch.
* [Y] Add some descriptions and refer relative issues for you PR.
* [Y] DO NOT include files inside `lib` directory.

Docsify publishing with AWS Amplify steps

---

docs/write-a-plugin.md

----
Missing trailing slash in the `Edit button` url
Result in:
```diff
- https://github.com/docsifyjs/docsify/blob/master/docsREADME.md
+ https://github.com/docsifyjs/docsify/blob/master/docs/README.md
```

Fix typo in edit button example

---

docs/configuration.md
src/core/config.js
src/core/router/history/base.js
src/core/router/util.js
test/unit/base.js
test/unit/util.js

Hello,
It's the same PR as https://github.com/docsifyjs/docsify/pull/593 thanks to @NoClin which allows relative path (fix #590). But I've added an option relativePath to enable it (like proposed in #657). By default it's disabled so it's backward compatible: no breaking changes. :)
I've tried to add some documentation, I hope it's clear enough.

feat: allows relative path, fixed #590

---

docs/more-pages.md

Document the changes made with https://github.com/docsifyjs/docsify/pull/557 as suggested in https://github.com/docsifyjs/docsify/issues/540 - enabling page title customisation via the sidebar links

document customising page title with sidebar

---

src/core/render/compiler.js

Add support for `ignoreSubHeading` when `loadSidebar` is false.
When `{docsify-ignore}` is applied on a heading, the generated sidebar still contains the header and its subheaders. When `loadSidebar` is false only the `sidebar()` method is called so the filtering needs to be inserted there. 
https://github.com/docsifyjs/docsify/blob/8cd786c9d533faa15b989f84f7ecf0d8f705a7c8/src/core/render/index.js#L93-L107
I used classic splice() method and for loops to remove the header and all it's subheaders because I saw this method being used `subSidebar()`. I was probably better to just use the `[].filter()` way but it works anyways.
---

Added filtering in sidebar for ignoreSubHeading

---

docs/deploy.md

**Summary**
This PR address:
* The docs contains typo Netlify's redirects file should be `_redirects` not `/redirects` ([reference](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/#the-redirects-file))
* Improve wording to be more understandable
Background: When looking for Deploying to Netlify docs I noticed above issue. I decided to contribute docs edit.
You have tested in the following browsers: …

fix netlify-redirects-file typo on docs and improve wording

---

docs/deploy.md

Add deployment instructions for ZEIT Now

---

docs/configuration.md
src/core/config.js
src/core/render/index.js
src/core/render/tpl.js

fixes #843 
**Summary**
Link target of repo's GitHub Corner opens  repo in current window/tab.
Fix : Link target of repo's GitHub Corner according to externalLinkTarget config. #835
**Other …

fix #835 :Link target of repo's GitHub Corner add new independent config `cornerExternalLinkTarget`. 

---

src/themes/buble.styl
src/themes/dark.styl
src/themes/dolphin.styl
src/themes/vue.styl

**Summary**
Fixes #967 - giving correct position to the token of markdown
|Before|After|
|--|--|
---

Fix: #967 token position markdown

---

src/themes/buble.styl

See #913 for the debate. TLDR:
I've separated strong and set it to 600. I've removed the `a { font-weight: 400}`, because it has overridden the headings h1, ... font-weight below.
(Links has blue color in the buble theme, so they do not need the slight font-weight increase. I also do not know how to keep font-weight and do not override headings, because headings are links to. I aware of CSS !important, but I think this solution is better for this situation.)

buble theme: fix strong font-weight increased to 600 (onto master branch)

---

docs/themes.md

**Summary**
The docs says there are 3 themes despite there being 4.
---

There are currently {three=>four} themes available.

---

docs/configuration.md

**Summary**
Tells people they can supply HTML in the `name` option.
---

docs: update docs for the `name` option

---

package-lock.json
package.json
src/core/render/embed.js

**Summary**
This pr fixes wrong indentation when embedding fragment of code.
Code:
Before:
After:
---

strip indent when embedding code fragment

---

src/plugins/search/search.js

Fix #1007 - Undefined error in search

---

src/core/render/compiler.js
src/core/render/index.js

fix https://github.com/docsifyjs/docsify/issues/516
----
In reference to #516 
Ensure the `h1` dom element created by the `autoHeader` feature is similar to the `ħ1` parsed from a markdown file.
```diff
-<h1>Title</h1>
+<h1 id="title">
+  <a href="#/?id=title" data-id="title" class="anchor">
+    <span>Title</span>
+  </a>
+</h1>
```
Please review this code carefully as I don't know if exposing the `renderer` is a good idea.

Ensure autoHeader dom result is similar to parsed H1

---

src/plugins/search/search.js

**Summary**
fix #582 and #824, I also encountered this problem, tried to fix and update a bit.
Fix the problem that the content of the table cannot be searched, But there are still some problems here, adding some descriptions will not search. 
To avoid wasting your time, it's best to open a **feature request …

fix #582 and #824

---

docs/cdn.md
docs/cover.md
docs/custom-navbar.md
docs/index.html
docs/language-highlight.md
docs/more-pages.md
docs/plugins.md
docs/pwa.md
docs/quickstart.md
docs/ssr.md
docs/themes.md
docs/vue.md

**Summary**
Pull request in relation to issue #1020 
This is a PR in relation to issue #1020 
---

changed the CDN from unpkg to jsDelivr #1020

---

src/core/config.js

**Summary**
close #860 
This PR fix two problems.
1. `document.currentScript` doesn't work in a callback or event handler, and will always return `null` with initializing config after `DOMContentLoaded` in docsify.
> It's important to note that this will not reference the <script> element if the code in the script is being called as a callback or event handler; it will only reference the element while it's initially being processed. - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript)
https://github.com/docsifyjs/docsify/blob/676f84cffa9d713fbad662371870d7db2109a9b3/src/core/index.js#L38-L41
2. There are some config fields coercions(e.g. `config.loadSidebar === true`) after merging from current executing script, but I think these coercions should not depend on …

fix config initialization and coercion

---

docs/helpers.md
src/core/render/compiler.js

**Summary**
Trying fix #1009 emojis in titles not working correctly ,  
I attempt to  think all the types likes  `:words:` as an emoji code that I wont replace it to empty(`' '`).
At the same time, it causes another proplem that it cant solve `foo::ddd::ccc`  as u want ever, the same as the time `15:02:55`. BUT i think it is acceptable, because ：
A: In my opnion, we doesnt render the  `foo::ddd::ccc` 's title id correctly now.
B: I think it is a[ good idea](https://github.com/docsifyjs/docsify/issues/1009#issuecomment-581972542) to put them within a code backticks that we can distinguish the title ,the emojis and the configurations easily at now.
> Here's an idea - for the weird code syntax cases that #708 was trying to fix, require users to put them within a code backticks to avoid any …

[fix #1009] Trying fix emojis in titles not working correctly.

---

.vscode/settings.json
docs/configuration.md
package.json

Documented `__colon__` tips to address issues like #745
**Why I added the comment link instead of showing how to do it ?**
Docsify docs is powered by docsify itself. So `__colon__` is converted into `:` in the docs as well.

chore: documented __colon__ tip

---

docs/configuration.md
packages/docsify-server-renderer/index.js
src/core/config.js
src/core/event/scroll.js
src/core/global-api.js
src/core/render/compiler.js
src/core/render/embed.js
src/core/render/index.js
test/unit/base.test.js
test/unit/render.test.js
test/unit/util.test.js

When using a template that has a sticky-header, clicking on the sidebar will
scroll the page under the header.
I added the option `headerHeight` (default = `0`) so that the content div will
be scrolled down that amount of pixels.
**Summary**
---

Adds option to specify an header height

---

src/core/event/index.js
src/core/fetch/index.js
src/core/render/index.js
src/core/router/history/hash.js
src/core/router/history/html5.js
src/core/router/index.js

Currently Docsify has the following behavior when it comes to scrolling:
* if `auto2top` is **enabled** then:
- _any_ change to a URL that includes an ID will scroll to that ID once loaded
- _any_ change to a URL without an ID always scrolls to the top once loaded
- therefore the browser's scroll restoration behavior is always nullified when moving back/forward in history or reloading the page
* if `auto2top` is **disabled** then:
- _any_ change to a URL that includes an ID will scroll to that ID once loaded
- moving back/forward in history and reloading the page uses the browser's scroll restoration behavior, but only if the target does not have an ID
- clicking a link to navigate to a page that does not include an ID maintains the current scroll position and usually ends up somewhere in …

feat(scroll): smarter scroll behavior

---

src/themes/basic/_layout.styl

**Summary**
Improve basic layout style a little.
| Before | After |
| ------ | ----- |
|![chrome_USCjuix3I3](https://user-images.githubusercontent.com/44045911/61186639-4a1b7a80-a69a-11e9-89d6-4f701d1f7285.png)|![chrome_EwsWCoKGVR](https://user-images.githubusercontent.com/44045911/61186646-51db1f00-a69a-11e9-9be0-ee10b8712cc2.png)|
|![Z7BNw0ZmFQ](https://user-images.githubusercontent.com/44045911/61186643-4e479800-a69a-11e9-8d90-7cd7ff985cf7.png)|![9Ev9NJW8Ig](https://user-images.githubusercontent.com/44045911/61186647-543d7900-a69a-11e9-9bc3-92137e6a2310.png)|
If yes, please …

improve basic layout style

---

docs/index.html

**Summary**
Hello, @anikethsaha there are two index.html, did I forget to modify this file?
---

Modify Chinese doc link

---

src/core/event/scroll.js
src/core/router/util.js

**Summary**
Fix #1136 and #1127
- [x ] Bugfix
- [x ] No
- [x ] Chrome
- [x ] Firefox
- [x ] Safari
- [x ] Edge
- [x ] IE
---

Fix #1136 and #1127

---

cypress/fixtures/tpl/docs.index.html
docs/index.html
docs/ssr.md
packages/docsify-server-renderer/README.md
server.js

Relates to one item mentioned in #945. 
Setting `maximum-scale=1.0` and `user-scalable=no` for the `viewport` meta content has a major detrimental impact on accessibility. Removing these values allows users to optionally zoom and preserves the default experience for other users.
I have made this fix in the default HTML template, but also updated docs and the SSR template.
* [Quick tip: Never use maximum-scale=1.0](https://a11yproject.com/posts/never-use-maximum-scale/) from The A11Y Project
* [Viewport guidelines for browser Zoom](https://web.dev/meta-viewport/) from web.dev (Google)
**Does this PR introduce a breaking change?** (check …

Improve accessibility of viewport meta by allowing page zoom (related to #945)

---

docs/_media/example-with-yaml.md
docs/embed-files.md
index.html
src/core/render/compiler.js
src/core/render/embed.js
src/core/render/utils.js
src/plugins/front-matter/index.js

**Summary**
This fixes #1129 where embed was pulling through the YAML header when rendering pages as an embed. I did not want to pull the YAML parser by default. There are no rendering hooks for embed so I added a flag to check to see if the front matter plugin is installed and if it is use it to strip the content before returning the txt to render to the page. 
FYI: I am not a JavaScript developer. :)
You have tested in the following browsers: (Providing a …

Updated embed to strip YAML front matter fixes #1129

---

src/plugins/search/search.js

**Summary**
Fix the id set in the title, resulting in wrong link when searching.
---

Fix the search error after setting the ID in the title

---

docs/helpers.md
src/core/config.js
src/core/render/compiler/link.js
src/core/router/history/html5.js

FIX #1046 
Cross-origin url cannot be redirected when  "externalLinkTarget" is set to "_self" and "routerMode" is set to "history".
Now, When  "externalLinkTarget"  set to "_self" and "routerMode", we will use `windows.open`  open url in current page instead.
what you should do is adding the `:crossorigin` next to  ur url
eg:
```md
[example.com](https://example.com/ ':crossorgin')  
```
**Summary**
You have tested in the following browsers: (Providing a detailed …

[fix #1046] fix  cross-origin url cannot be redirected when  "externalLinkTarget" is set to "_self" and "routerMode" is set to "history".

---

src/core/render/compiler/image.js
test/unit/render.test.js

**Summary**
When image is resized by providing only a `width`, it does not set the `height`. Let html resize automatically to respect the aspect ratio.
Fixes #1064 .
---

default html img resize if no height included

---

packages/docsify-server-renderer/index.js
src/core/event/scroll.js
src/core/global-api.js
src/core/render/compiler.js
src/core/render/compiler/link.js
src/core/render/embed.js
src/core/render/index.js
test/unit/base.test.js
test/unit/render.test.js
test/unit/util.test.js

fix: fixed target and rel issue (fixes #1183)

---

src/themes/basic/_coverpage.styl

**Summary**
fix cover rendering bug, the width of cover has not filled the whole page
before
sometimes display not well but not always
after
---

fix: rendering cover width bug

---

src/core/render/embed.js

**Summary**
fix #970 - updated the insertion of embedded tokens so it correctly handles embedded token results returning in any order
The previous implementation incorrectly assumed that contents of embedded content would be returned in the order they were requested in the document.  This created unpredictable race conditions when multiple embeds were included.
I have run into this issue with embedded markdown, and have only attempted test-cases surrounding the markdown content specifically.
---
* [X ] DO NOT include files inside `lib` directory.

fix #970, updated the insertion of embedded tokens for async returns

---

CHANGELOG.md
docs/index.html

**Summary**
- [x ] Docs
Updated docs site dark and light mode with switch and redesigned search bar using [docsify-darklight-theme](https://www.npmjs.com/package/docsify-darklight-theme) you can refer the docs and see full preview [here](https://boopathikumar018.github.io/docsify-darklight-theme)
- [x ] No
- [x ] Chrome
- [x ] Firefox
- [ x] Edge
If adding a **new …

Updated docs site dark and light mode with switch and redesigned search bar using docsify-darklight-theme

---

build/build.js
build/css.js
build/mincss.js
build/ssr.js
package-lock.json
package.json
src/core/global-api.js
src/core/index.js
src/core/util/dom.js
test/unit/docsify.test.js

**Summary**
Add error handling to build processes so they don't silently fail.
---

Add build error handling

---

src/plugins/search/search.js

**Summary**
The previous commit #1015 only fixed the situation where there was no content before the table. like this:
```
| C Name  | Value | Description       |
| ------- | ----- | ----------------- |
| Success | 0     | Success           |
| EPERM   | 1     | Operation not per |
```
But this one below is not searchable.
```
Here are some descriptions....
| C Name  | Value | Description       |
| ------- | ----- | ----------------- |
| Success | 0     | Success           |
| EPERM   | 1     | Operation not per |
```
If yes, please describe the impact and migration path for …

fix: search does not find the contents of the table

---

src/themes/basic/_coverpage.styl
src/themes/basic/_layout.styl

**Summary**
For devices having a width of `768px` or less the sidebar is overlapped by the cover page
This PR fixes that by sliding the cover page over, similar to the content page
The bug is reproduced by loading the page on a device browser having a screen size of `786px` or less
and clicking the `sidebar-toggle` button
**Before**
**After**
- Fix #1213 

fix #1213 

---

docs/embed-files.md

**Summary**
Added gist instructions to Embed Files page. Closes #982.
Also cleaned up the grammar on the first part of the page.
---

fix #932 - Add embed gist instructions to Embed Files

---

build/build.js

**Summary**
This PR introduces an error handling method for missing dependencies as described in issue #1210 . `onwarn` intercepts warning messages and when `message.code === 'UNRESOLVED_IMPORT'` it means there is an unresolved or missing dependencies. Prior to this PR, a warning message would be logged to the console. The changes made throw an error instead, which can be handled by the appropriate error handler
*Before:*
```
lib/plugins/front-matter.min.js
lib/plugins/front-matter.js
lib/plugins/search.min.js
lib/plugins/search.js
'medium-zoom' is imported by src\plugins\zoom-image.js, but could not be resolved – treating it as an external dependency
'medium-zoom' is imported by src\plugins\zoom-image.js, but could not be resolved – treating it as an external dependency …
```

fix: #1210 - Add error handling for missing dependencies

---

docs/quickstart.md

**Summary**
Updated docs with example of using a specific version of docsify while getting started, instead of the default version. 
Issue #780 requested changes in the CLI, opened a PR there as well with the changes [#107](https://github.com/docsifyjs/docsify-cli/pull/107)
To avoid wasting your time, it's best to …

fix: Updated docs with instructions for installing specific version #780

---

src/core/render/tpl.js

**Summary**
This PR fixes issue #1173
Before:
After
**Todo**
Add integration test using cypress
*Blocker:* figuring out how to test multiple configs
fix issue #1173 

Fix: 1173 - fixed onlycover flag in mobile

---

src/core/render/tpl.js
src/themes/basic/_coverpage.styl

fix: after setting the background image, the button is obscured

---

README.md
docs/README.md
docs/_coverpage.md
docs/cover.md

**Summary**
fix issue #1211, will create a separate branch for the Lighthouse integration
---

Remove bundle size from the home page and documentation

---

src/core/event/sidebar.js
src/core/render/tpl.js

**Summary**
fix #1178 
replace #1179 
---

feat: Add title to sidebar links

---

docs/index.html
index.html
src/core/event/scroll.js

**Summary**
* Remove unused `formatUpdated` config
* Sync index.html, Add `pure.css` and `prism-php.min.js`
* Fix variable `top` is redundant 

style: Update index.html and scroll.js

---

src/plugins/search/search.js

**Summary**
Fix search error when exist translations documents.
For example: Chinese documents can be searched in English documents

fix: Fix search error when exist translations documents

---

src/plugins/search/index.js

**Summary**
Fixes typo (`componet -> componeNt`) in the search plugin `index.js`.

fix(search/index.js): typo

---

src/plugins/search/search.js

fix: Search plugin: matched text is replaced with search text

---

docs/plugins.md
index.html
src/plugins/search/index.js
src/plugins/search/search.js

**Summary**
This option allows to dynamically choose the index path depending on the path prefixes in auto mode. Thus, different path namespace could avoid index intersection (e.g., when having multiple locales):
```js
// complete configuration parameters
search: {
// ...
// Use different indexes for path prefixes (namespaces).
// NOTE: Only works in 'auto' mode.
//
// When initialiazing an index, we look for the first path from the sidebar.
// If it matches the prefix from the list, we switch to the corresponding index.
pathNamespaces: ['/zh-cn', '/ru-ru', '/ru-ru/v1'],
// You can provide a regexp to match prefixes. In this case,
// the matching substring will be used to identify the index
pathNamespaces: /^(\/(zh-cn|ru-ru))?(\/(v1|v2))?/
}
```
Closes #1303.
Array version is used here: …

FEAT: add pathNamespaces option to search plugin

---

docs/configuration.md

Minor changes.
Solely for improving readability.
**Summary**

Make grammatical changes

---

src/core/router/history/hash.js

**Summary**
fix: the uncaught typeerror when el is null. close #1154 

fix: the uncaught typeerror when el is null

---

docs/more-pages.md
src/core/render/compiler.js
src/core/render/compiler/headline.js
test/unit/render.test.js

Ref and close #441
This should also close https://github.com/docsifyjs/docsify/issues/767
**Summary**
This PR prevents `{docsify-ignore}` and `{docsify-ignore-all}` to be rendered inside other markdown engines like on Github.
**Tests**
```
$ mocha ./test/**/*.test.js …
```

Convert {docsify-ignore} and {docsify-ignore-all} to HTML comments

---

docs/index.html
index.html

**Summary**
fix: {docsify-updated} in the sample code is parsed into time. close #1320 
Since it is full-text matching, we can only use load remote files to avoid this problem

fix: {docsify-updated} in the sample code is parsed into time

---

cypress/fixtures/tpl/docs.index.html
cypress/integration/routing/fallback.spec.js
src/core/fetch/index.js

**Summary**
When resolving fallback page for the path (`fallbackLanguages` option), we should consider the original path, not the file location (which could be different when aliases are used).
This patch is used in [this repo](https://github.com/test-prof/docs) and "deployed" at https://test-prof.evilmartians.io/. …

FIX: fallback page should use path not file location

---

docs/index.html
index.html

Docs: added carbon ad

---

package.json

chore: Remove the src directory from packages.json's files

---

src/core/event/sidebar.js

**Summary**
fix #1359
Bugs caused by #1286

fix: sidebar title error

---

src/plugins/search/search.js

**Summary**
I fixed `#1356` and found another error.
```js
const path = paths[0];
if (Array.isArray(config.pathNamespaces)) {
namespaceSuffix =
config.pathNamespaces.find(prefix => path.startsWith(prefix)) ||
namespaceSuffix;
} 
```
`path` is `undefined` when only a readme file is present.
To avoid wasting your …

fix: Cannot read property 'startsWith' of undefined

---

src/core/render/compiler/code.js

**Summary**
the Prism [`highlight()`](https://prismjs.com/docs/Prism.html#.highlight) method requires three arguments:
```
(static) highlight(text, grammar, language) → {string}
```
The last one should be the name of the language. Without the third argument, the `js-templates` (`components/prism-js-templates.js`) component does not work (for highlighting template literals).
Without the third argument:
With the third argument:
You have tested in the following …

fix: add missing argument for highlighting code

---

docs/configuration.md
docs/helpers.md

**Summary**
Due to the #1379 ，there is necessary to mention this configuration `crossOriginLinks`.

docs: add crossOriginLinks configurations details

---

src/plugins/search/search.js
test/e2e/sidebar.test.js

fix: Can't search homepage content

---

src/core/render/compiler.js
src/core/render/compiler/headline.js
src/core/render/utils.js
test/unit/render-util.test.js

**Summary**
Fix #1069 , the sidebar should always direct to current site content.
SO, Removing the sidebar titles'  `<a>` tag (if had) when the header with a link.
fix #1069 

fix: the sidebar links to another site.

---

index.html
test/e2e/search.test.js
test/e2e/sidebar.test.js

fix: search on homepage test

---

src/core/render/tpl.js
test/unit/render-util.test.js

**Summary**
fix https://github.com/docsifyjs/docsify/issues/1353#issuecomment-699716563 and fix #1408

fix: title error when sidebar link exists with html tag

---

src/core/render/slugify.js
test/unit/render-util.test.js

fix: slugs are still broken when headings contain html

---

src/core/event/sidebar.js
test/e2e/sidebar.test.js

**Summary**
This PR fixes URL decoding problem in sidebar, reported in #1032. It builds on previous work in #1043, but with rebased and updated fix (just 1 line now).
fix #1032, close #1043

fix: sidebar active class and expand don't work as expect when use "space" in markdown filename

---

docs/quickstart.md

**Summary**
- Slightly tweak Python server instructions to be more generic
- Clarify the section about customizing the main container

docs: Improve Quick start instructions

---

src/core/fetch/index.js
src/core/render/compiler/link.js
src/core/render/embed.js
src/core/render/index.js
src/plugins/search/search.js

**Summary**
Modern convenience methods like `Array.prototype.find()` and `String.prototype.startsWith()` are not compatible with legacy browsers like IE11. This PR replaces those methods with legacy-compatible approaches that accomplish the same thing.

fix: Use legacy-compatible methods for IE11

---

docs/index.html
src/core/render/index.js

**Summary**
* Replace template literals
* Replace `Object.entries`
* Replace `Object.assign`
* Replace method shorthand (e.g. `{ foo() {} }` vs `{ foo: function() {} }`)

fix: Replace ES6 usage for IE11 compatibility

---

docs/themes.md

**Summary**
IE11 was throwing an error when loading the "Themes" page due to missing semicolons in the page `<script>`.

Fix: Theme preview in IE11

---

docs/index.html
index.html

chore: Fix missing carbon

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
docs/README.md
docs/index.html

**Summary**
According to #1224, make changes to separated PRs.
Change Gitter to Discord throughout project firstly. 

chore: change Gitter to Discord throughout project.

---

docs/configuration.md

The expression in alias `(+*)` is invalid and a correct working method would be `(.*)`
**Summary**

docs: Updated alias

---

src/core/fetch/index.js
test/e2e/security.test.js

Fix #1477. Fix #1126. Follow-up to #1489.
**Summary**
Handles malformed remote URLs that contain more than two forward slashes (e.g., `////////domain.com/file.md`)

fix: isExternal check with malformed URL + tests

---

CHANGELOG.md
docs/README.md
docs/_coverpage.md
docs/configuration.md
docs/index.html
package-lock.json
package.json
packages/docsify-server-renderer/package-lock.json
packages/docsify-server-renderer/package.json
src/core/fetch/index.js
src/core/util/core.js
src/plugins/search/search.js
test/e2e/search.test.js
test/e2e/security.test.js
test/integration/__snapshots__/docs.test.js.snap
test/unit/core-util.test.js

> ## Do Not Merge
***
|Changelog|
|-|
- Replace ES6 usage for IE11 compatibility (#1500)
- Fix theme switcher in IE11 (#1502)
- Fix isExternal check with malformed URL + tests (#1510) 
- Support search when there is no title (#1519)
- Fix missing carbon (#1501)
- Change Gitter to Discord throughout project (#1507)
- Upgrade docsify from 4.11.6 to 4.12.0 (#1518) 
- Add test cases on isExternal. (#1515) 
- Updated alias (#1511) 
- Update Vercel logo link (#1520)
|Blocking|
|-|

[Release]: v4.12.1

---

src/plugins/search/component.js

**Summary**
fix https://github.com/docsifyjs/docsify/issues/1526

fix: Cannot read property 'classList' of null

---

src/plugins/search/search.js

`escapeHtml` was removed in support of search accents, which may cause some problems. #1549
After adding it question 2 will appear again. https://github.com/docsifyjs/docsify/pull/1434#pullrequestreview-552172033
What's the best way to do it? 
Bugfix
close #1549

fix: Add escapeHtml for search

---

src/themes/buble.styl

buble theme missing generic fallback font
close #1565

fix: buble theme missing generic fallback font

---

docs/embed-files.md

As per to #1558 , update doc details about the default behaviors  of docsify.
close #1558 
Docs

docs: add note on video/media attrs.

---

docs/plugins.md

In Chrome 90.0.4430.212（正式版本） （64 位）
Use
```bash
docsify serve .
```
run the server.
If user use plugin
```html
<script src="//cdn.jsdelivr.net/npm/docsify-copy-code"></script>
```
The console of Chrome will show
```
DevTools failed to load SourceMap: Could not load content for http://cdn.jsdelivr.net/npm/docsify-copy-code.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
When change src
```html
<script src="//cdn.jsdelivr.net/npm/docsify-copy-code/dist/docsify-copy-code.min.js"></script>
```
The warning message will disappear.
Docs
None

docs: src of docsify-copy-code

---

docs/embed-files.md
src/core/render/utils.js
test/unit/render-util.test.js

I fixed a bug where `":include"` is not handled like `':include'`. This is not working because the type of quotes are not supported. The default prettier configuration changes the `''` to `""`. And if you have auto format toggled on, you're not be able to save the file with the right quotes.
I added added the `"` also the the replace regex
```js
str = str
.replace(/^('|")/, '')
.replace(/('|")$/, '')
```
closes #1597 
closes #1587 
closes #1555 
closes #1005

fix: allow also " inside of an embed

---

docs/write-a-plugin.md

Update docsify-updated to prevent replacement
before | after
---|---
docs
#1573

docs: Update docsify-updated to prevent replacement

---

docs/configuration.md
docs/cover.md
docs/markdown.md
docs/more-pages.md
docs/plugins.md
docs/quickstart.md
docs/write-a-plugin.md

While referencing the documentation, I noticed a few phrases that could
be changed to sound more natural. I tried to keep the original meanings.
This change improves the phrasing of the English translation of the documentation. It uses more natural sounding English phrases. Only two sections are covered in this PR: the Getting Started and Customization sections.
No UI changes.
Docs

docs: improve English wording (Getting Started/Customization)

---

docs/write-a-plugin.md
index.html

Add the config `formatUpdated: '{YYYY}/{MM}/{DD} {HH}:{mm}'` in docs to make this plugin more clearly.
Docs 

docs: update formatUpdated

---

README.md
docs/README.md

We modified the CI so some badges are useless.
There is some outdated content in these two PRs, and new PRs can be submitted if desired.
close #1224 
close #1274
Docs

docs: update readme

---

.gitignore
src/themes/basic/_coverpage.styl

Fix #381. Replacement PR for #1514.
**Before:**
**After:**
Fix
#381

fix: Coverpage when content > viewport height

---

README.md

The link to netlify has not been updated for a long time.

chore: update develop branch preview link

---

src/core/render/index.js
test/e2e/plugins.test.js

fix #449 (see for details)
- Fix invocation order of `doneEach` and `ready` hooks  when using asynchronous `afterEach` hook(s).
- Update plugin tests to verify hook order
**Before**
`doneEach` and `ready` hooks are properly invoked after all _synchronous_ `afterEach` hooks are complete.
```
afterEach() - Sync
afterEach() - Sync
afterEach() - Sync
doneEach()
ready()
// ** Content rendered **
```
With asynchronous `afterEach` hooks, `doneEach` and `ready` hook are improperly invoked before the first async `afterEach` hook.
```
afterEach() - Sync
doneEach()           // <-- Bug
ready()              // <-- Bug
afterEach() - Async
afterEach() - Sync
// ** Content rendered **
```
**After**
`doneEach` and `ready` hooks are invoked after all `afterEach` hooks are complete, regardless of …

Fix: ready/doneEach order with async afterEach

---

docs/write-a-plugin.md

A few minor fixes/updates to the "Write a Plugin" page. No significant content changes.
Docs

docs: Minor fixes to plugin docs

---

README.md
docs/README.md
docs/index.html

chore: update vercel link

---

docs/write-a-plugin.md

This simple change to the plugin template provided in the docs ensures that plugins are inserted into the `$docsify.plugins` array in the order that the `<script>` tags appear in the DOM. Before this change, plugins were always inserted at the beginning of the plugins array which can (and has) caused issues when the order of plugin execution is important.
Docs

Docs: Fix plugin insertion order in docs

---

src/plugins/search/search.js
test/e2e/search.test.js

When the content is empty, the `postContent` of `post.body` is `undifined`, therefore, here will get ex while `substring` on an `undefined` str `handlePostContent`.
```md
---
---
Some content here
```
close #1876
Bugfix

fix: fix search with no content.

---

src/core/render/index.js

fix #1907 
When query and remove the sidebar again, there contains `["null","null"]` nodes for removing  which already moved.

fix: filter null node first.

---

docs/configuration.md
docs/helpers.md
src/core/config.js
src/core/render/compiler/link.js
src/core/router/history/hash.js
src/core/router/history/html5.js

the crossOriginLinks option is no longer needed, remove misspelled "crossorgin" link helper, and instead detect cross origin links and don't handle them as internal
External links are now navigable by default when `routerMode` is `history`, regardless of the `externalLinksTarget` value. 
The `crossOriginLinks` option was added as a way to force external links to not be handled as internal.
Instead, that feature has been removed, and now we use `isExternal` to check for external links, and avoid handling them as internal.
The value of an `<a>` tag's `target` is no longer used as our external link check.
Bugfix
Docs
The `crossOriginLinks` option is now ignored. I don't think this is breaking. I think people want external links to work properly, so at worst some people will have listed all …

ref #1803: fix cross-origin links in history router mode

---

src/core/util/core.js
test/unit/core-util.test.js

Fix an xss vulnerability that was fed via email.
Fix https://github.com/docsifyjs/docsify/issues/1477#issuecomment-1594666599

fix: enhancement of isExternal

---

.codesandbox/ci.json
sandbox.config.json

We have GitHub Action and Vercel, so we can eliminate the need for codesandbox.
And codesandbox limits the build memory, so it often fails.

chore: remove codesandbox

---

index.html

We currently have two `index.html` files (why is that again?). One file was not loading Vue stuff.
Without the Vue support in Vercel builds, we were unable to fully verify pull request builds, therefore unable to confirm if Vue broke or not. Now we can manually check Vue functionality for PRs.
Add Vue support to the index.html file that didn't have it.
No

chore: add missing Vue support for Vercel builds

---

docs/configuration.md

Fix the `themeColor` config doc changed in #2114 .
```
> <style>
>   :root {
>     --theme-color: deeppink;
>   }
> </style>
```
the markdown takes a mistake to treat it as HTML style. See [Pink Configuration preview](https://docsify-preview-git-fix-vue-in-vercel-deployments-docsifyjs.vercel.app/#/configuration) as reproduct.
Docs

update(doc): fix themeColor in configuration.

---

CHANGELOG.md
package.json
src/core/util/ajax.js
src/core/util/dom.js

This PR fix the typos as seen in various files.
```pseudo
seach > search
extenstion > extension
compatbility > compatibility
implmentation > implementation
laoded > loaded
```
No

chore: Fix typo in multiple file of docsify

---

.github/dependabot.yml

Also ignore patch and minor bumps for dependencies, and ignore patch bumps for github actions. This will let us focus on major updates.
Docsify is a static website, there's isn't much of a security concern with checking every patch bump. We aren't making a server application for people to put across their servers, we're simply reading markdown and outputting HTML on the client, nothing very critical at all, so we don't need to spend so much time with noisy updates.
Repo settings
No
N/A

reduce dependabot frequency from weekly to monthly, get rid of email spam

---

.gitattributes

It is recommended by Prettier to use LF endings for all files including in Windows, and they officially recommend to set this option in .gitattributes file for consistency, and LF is the default in Prettier 2 or higher. The lack of this file bit me in another project whose build failed in Windows in GitHub Actions due to `prettier --check` failing in Windows with default LF mode.
More info: https://github.com/prettier/prettier/issues/7825#issuecomment-602171740
Repo settings
No
N/A

chore: Create .gitattributes to prevent errors with Prettier in Windows

---

src/themes/basic/_layout.styl

See title and original issue (below).
#2225 
Feature
- No documentation changes required
- No automated tests required
No

Feat: Prevent focus on hidden sidebar

---

docs/configuration.md
src/core/config.js
src/core/fetch/index.js
src/core/render/index.js
src/core/router/history/hash.js
src/core/router/history/html5.js
src/core/util/ajax.js
test/e2e/configuration.test.js
test/e2e/plugins.test.js
test/e2e/virtual-routes.test.js

- Add response status to internal route object
- Expose response status to plugin hooks to allow for custom error handling.
- Update default error page content with error status and status text (e.g. "401 - Not Authorized", "500 - Internal Server Error", etc.) instead of displaying "404 - Not Found" for *all* errors.
- Fix issue where initial site render was incomplete when content fetch failed (e.g., no sidebar, plugins halted, etc.) 
- Fix issue where empty markdown pages/routes were handled as 404 errors.
- Add tests to verify default error handling
- Add tests to verify `notFoundPage` error handling
- Add tests to verify response data availability via plugins
See #2294 for details.
```js
window.$docsify = {
// ...
plugins: [
function (hook, vm) {
hook.beforeEach(html => {
const { …
```

Feat: Improved error handling and response status availability

---

docs/configuration.md

If name prop is not set logo is not visible, this should be described to user
#1646
Also PR #2344 
Docs
No

docs: Update logo doc

---

docs/_media/example-with-yaml.md
docs/embed-files.md
docs/index.html

- Fix front matter broken
- Update document
Fix #168 
Bugfix
No

chore: fix front matter broken

---

src/core/config.js

The following deprecation warning was spamming the console even when `$docsify.themeColor` was not being used: 
```
$docsify.themeColor is deprecated. Use a --theme-color property in your style sheet. Example:
<style>
:root {
--theme-color: deeppink;
}
</style>
```
This console message will now only appear when $docsify.themeColor is used.
None
Bugfix
N/A
No

fix: prevent unnecessary themeColor deprecation notice

---

build/build.js
build/mincss.js
server.configs.js

Fixes two development issues:
1. Hot reload was not working because the docs site was loading `lib/docsify.min.js` which was only updated on "production" builds. The build now generates minified and non-minified bundles for all builds.
2. Source maps are now generated for all `.min.js` files in `/lib/`. This solution is best for troubleshooting during development because source maps provide unminified source code along with accurate file and line locations on errors. Using non-minified bundles for development was previously discussed, however this approach does not provide accurate source file and line locations.
None
Bugfix
N/A
No

fix: dev mode hot reload and add sourcemaps

---

src/core/event/index.js

Fixes an issue the new (unreleased) "Skip to Content" link that caused an immediate jump to to the content (instead scrolling) and the main content to scroll down (instead of being static) into place. 
**Example of bug** (develop branch preview w/ Chrome 123)
The incorrect behavior is the result of three separate things occurring at the same time:
1. By default, browsers will automatically scroll any offscreen element that receives focus into view. This is the correct behavior for accessibility purposes because the focused item should be in view.
2. Clicking the "Skip to Content" link places the focus on the main content area. This is the correct behavior for accessibility purposes because the focused item should be in view. However, by placing the focus on an off-screen element, the …

fix: skip-to-content scroll behavior

---

docs/deploy.md

Add stormkit as deployment platform
Docs
No

docs: add stormkit as deployment platform

---

docs/configuration.md
docs/deploy.md
docs/index.html
docs/vue.md
package-lock.json
package.json
server.configs.js
src/core/render/compiler/code.js
src/core/render/index.js
test/e2e/vue.test.js

- **Remove Vue v2 dependencies, tests, and documentation**
Vue.js v2 has reached [EOL status](https://v2.vuejs.org/eol/).
- **Update Vue v3 dependencies, tests, and documentation**
- **Support Vue text interpolation in code blocks**
See #1812 for details. This is now supported by wrapping a code block in an element with a `v-template` attribute:
````markdown
<div v-template>
```
{{ message}}
```
</div>
````
#1812
Bugfix (in docs)
Docs
No

Update Vue dependencies, tests, and documentation. Fix text interpolation in code blocks.

---

.github/workflows/test.yml

Fix the `test.yml` workflow, correct it to be trigger on pull request.
Bugfix
Yes
No
No

fix(ci): run test action for pull requests

---

src/core/render/compiler.js
test/e2e/sidebar.test.js

For docsify `autoHeader` config, there is a separately call to renderer of marked.
Fix the autoHeader's heading marked adaption function and add test case for this.
Bugfix
Yes
No

fix: auto header config heading generate func

---

package-lock.json
package.json
src/plugins/search/search.js
test/integration/example.test.js

use dexie.js instead of localStorage.
Maybe we also need to remove JSON parsing?
close #2281
close #1538
Feature
No

feat(search): use dexie.js instead of localStorage

---

docs/quickstart.md

Mino changes since we now have `adding-pages` instead.
I find this when review the changes we made recently.
And I know we will have next around to review docs also, just fix it btw. :)
Docs
Yes
No

docs: correct docs wrong link for adding pages

---

src/core/event/index.js
src/plugins/search/component.js

Currently, on the v5 changes, each headings/links on the sidebar has the `title` via `#addTextAsTitleAttribute`.
https://github.com/docsifyjs/docsify/blob/42f25482fa1ea6ec666800145f6da33e9119aa8c/src/core/render/index.js#L20
After the `event` refactor, the page `title` update function changed, especially the search page title.
---
Example from our site.
v4:
On the main content  load the page title such as `Configuration`, no matter you switch the sections to `Configuration`.
or directly jump to its sub headings [configuration?id=alias](https://docsify.js.org/#/configuration?id=alias).
The page title is always `Configuration`.
v5 as-is:
On the main content  load the page title such as `Configuration`, switch the sections to `Configuration`. (same to v4 )
:warning:  directly jump to its sub …

fix: sync the page title regarding the title config

---

docs/markdown.md

correct mermaid docs after upgrade marked, and mentioned its limitation.
We should adoption the mermaid to resolve the async issue in #1433 then.
Docs
Yes
No

docs: correct mermaid docs after upgrade marked

---

docs/deploy.md

I updated the **Netlify** section in the deploy docs. I found it difficult to deploy my docsify doc page to Netlify following the description outlined here. After figuring out how to successfully deploy to Netlify, I thought its wise to update it, to help others.
- Docs
- [x ] No

docs: Update Netlify deployment

---

src/plugins/zoom-image.js

- Support dark mode for zoom-image plugin.
- Add z-index, Fix: 
Fix #2508
Feature
No
Yes
No

feat: Support dark mode for zoom-image plugin

---

src/core/event/index.js
src/core/render/compiler.js

- Added a flag (`isInitialLoad`) to skip the first callback execution of the IntersectionObserver on page load.
Fix #2504
Fix #2509
Bugfix
No
Yes
No

fix: Prevent initial unnecessary IntersectionObserver callback execution

---

src/plugins/search/markdown-to-txt.js

see https://github.com/markedjs/marked/blob/master/src/Renderer.ts#L53
Fix: 
https://docsify-preview.vercel.app/preview/#/zh-cn/
```
marked.esm.js:21 Uncaught (in promise) Error: Token with "link" type was not found.
Please report this to https://github.com/markedjs/marked.
at ne.parse (marked.esm.js:21:1)
at Object.heading (markdown-to-txt.js:62:25)
at ne.parse (marked.esm.js:21:1)
at parse (marked.esm.js:21:1)
at Object.parse (marked.esm.js:15:21)
at Function.oe [as parse] (marked.esm.js:15:21)
at de (markdown-to-txt.js:191:28)
at search.js:154:36
at Array.forEach (<anonymous>)
at search.js:109:10
```
Bugfix 
No
Yes
No

fix: parse heading error

---

build/release.sh
docs/_navbar.md
docs/index.html
package.json
test/integration/__snapshots__/docs.test.js.snap

We are about to release version V5.0.0-RC1, and since the documentation for these languages is not up to date and I am not sure if the previous maintainer is willing to continue to maintain it, I will ping here and if there is time to continue to maintain it, then it can be added back.
> btw, while we can use Ai for translations, we lack native language speakers for confirmation, and if there is no one to maintain it, then I'd still recommend removing it.
> We also welcome new contributors! ❤️
- [es](https://github.com/docsifyjs/docs-es) @SidVal
- [ru](https://github.com/docsifyjs/docs-ru) @lex111
- [de](https://github.com/docsifyjs/docs-de) @SidVal

chore: retire outdate multiple languages

---

docs/index.html

There is h6 content in the document, but the search configuration defaults to h2, so the relevant content is not searched.

chore: add depth configuration for search

---

src/themes/shared/_classes.css

fix: exclude app-name-link from sidebar text overflow styling

---

src/core/event/index.js

fix: enhance focus handling by adding smooth scroll to content area

---

package.json

We no longer need the themes directory.

chore: remove themes directory from package.json files list

---

docs/configuration.md
src/core/router/history/hash.js

This PR improves hash navigation handling by correctly setting the navigating flag even when the clicked link points to the current hash.
Close #522
Bugfix
No

fix: handle hash navigation to prevent duplicate callbacks

---

docs/configuration.md
src/core/render/index.js

- Use querySelector instead of getElementsByTagName for clarity
- Avoid redundant DOM wrapping by directly accessing firstElementChild
- Add null check to prevent potential DOM insertion errors
Close #810

refactor: simplify auto header insertion logic

---

.vscode/launch.json
test/config/jest.setup-tests.js

chore: update launch configuration

---

src/core/event/index.js
src/core/render/compiler/heading.js
src/core/router/util.js
src/plugins/search/component.js
src/plugins/search/search.js

- Searching with ?s= may trigger an XSS injection， escape the search str.
- Introduce `function stripUrlExceptId` to ensure sidebar links only contains `id` as anchor.
As-is
> v4
---
> v5 rc1

fix: escape HTML in search keywords and trim sidebar id

---

src/themes/addons/core-dark.css
src/themes/shared/_coverpage.css
src/themes/shared/_vars.css

CSS updates for the following:
- Fix for Coverpage title link colors 
- Fix for Transparent iframe support in dark mode
- Fix for inline codeblock contrast within shaded table rows
Also available for review and testing in codesandbox:
https://codesandbox.io/p/sandbox/docsify-v5-css-issues-6r26v7
View `index.html` to uncomment related CSS fix to see proposed changes, etc.
And here is the same test Docsify site using the updated theme files in this PR:
https://paulhibbitts.github.io/docsify-v5-css-issues/#/
(not sure why clicking on Quick start on Coverpage only scrolls down halfway, I think this is a pretty recent issue and also seems to be on https://preview.docsifyjs.org/#/ now but not in RC-1 https://paulhibbitts.github.io/docsify-v5-rc-1-coverpage/)

style: CSS updates for coverpage, iframe dark mode transparency and codeblock contast

---

src/core/render/compiler/link.js
test/integration/render.test.js

Close #1929
Close #2300
Close #1987
Convert the link to an absolute path.

fix: update relative link handling

---

docs/themes.md
src/core/render/slugify.js
test/unit/render-util.test.js

While generating slugs, we noticed two issues affecting consistency:
1. **Invisible FE0F (Variation Selector-16)**
* Certain symbols can appear either as text or emoji, depending on whether they are followed by `U+FE0F`.
* Text style: `✏` (U+270F)
* Emoji style: `✏️` (U+270F U+FE0F)
* If `FE0F` is not explicitly removed, the slug may contain invisible characters, leading to inconsistent URLs.
2. **NFKD decomposition side effects**
* Using `normalize("NFKD")` decomposes precomposed characters like `é` (`U+00E9`) into `e + U+0301`.
* This results in visually identical strings with different underlying byte sequences, which can cause issues in comparisons and storage.
* **Remove `U+FE0F` explicitly**
* Ensures emoji and text variants of the same symbol produce identical slugs.
* Example:
* …

fix: normalize slugs to NFC and remove emoji variation selector

---

src/core/event/index.js
src/core/render/tpl.js

fix: enhance accessibility for sidebar toggle button

---

src/core/render/compiler.js
src/core/render/compiler/tableCell.js
src/core/render/embed.js

| before | after |
| -- | -- |
| <img width="852" height="390" alt="image" src="https://github.com/user-attachments/assets/100a8c2c-1aa6-4997-b7fe-963855d6a296" /> |  <img width="1228" height="452" alt="image" src="https://github.com/user-attachments/assets/b421604e-4bbb-4fc7-9f00-dc994430124c" /> |
Fix #398

feat: enhance embed handling for table cells
